### ISSUE TITLE
RFC - Fully custom breakpoints object

### ISSUE THREAD

**Issue by JarrodMFlesch** [faceless-ui/window-info#16]
With the current setup, we are only exposing/allowing certain breakpoints to hit and report back to the user and they are all `max-width` based breakpoints that range from `xs/s/m/l/xl`

I think a better approach would to allow the user to supply (almost) the entire object and that would have the potential to look exactly how the user wants it to. Take the following as an example, the user could use their own descriptive keys that fit their use case (only using these to show the customization potential):

```javascript
{
   iphoneXS: '(max-width: 300px)',
   iphoneX: '(max-width: 400px)',
   ipad: '(max-width: 1000px)',
   iphoneXMaxHeight: '(max-height: 800px)',
}
```

With this approach, breakpoints would be 100% customizable, which would be ideal in many cases.

Then we would create the necessary `window.matchMedia` queries to fire when the window changes height/width and report back using the keys from their breakpoints object.

**Comment by jacobsfletch** [comment]
This is great, and along the lines of what I would have suggested instead of PR #15
